steps:
- name: 'gcr.io/cloud-builders/docker'
  args: ['build', '-t', 'gcr.io/awesome-project/awesome-project:$SHORT_SHA', '.']
- name: 'gcr.io/cloud-builders/docker'
  args: ['push', '-t', 'gcr.io/awesome-project/awesome-project:$SHORT_SHA']
- name: 'gcr.io/cloud-builders/gloud'
  args: ['beta', 'run', 'deploy', 'awesome-project', '--region=europe-west1', '--platform=managed', '--image=gcr.io/awesome-project/awesome-project:$SHORT_SHA']

